"use client";
/**
 * Logo kit packaging: SVG + PNG (1x/2x/4x) per variant, favicon set and a
 * README with the usage rules. JSZip is loaded on demand.
 */
import type { Genome, LogoVariantKey } from "@/lib/genome/schema";
import { pngsToIco, svgSize, svgToPngBlob } from "@/lib/raster";
import { slugify } from "@/lib/utils";

export interface KitVariant {
  key: LogoVariantKey | string;
  svg: string;
  label?: string;
}

export interface KitOptions {
  /** Width in px of the @1x PNG (height follows the aspect ratio). Default 512. */
  baseWidth?: number;
  /** Scale factors to render. Default [1, 2, 4]. */
  scales?: number[];
  includePng?: boolean;
  includeFavicon?: boolean;
  /** Background colour for PNGs of light-on-dark variants (mono-light); transparent when omitted. */
  monoLightBackground?: string;
  onProgress?: (message: string, fraction: number) => void;
}

export const VARIANT_LABELS: Record<LogoVariantKey, string> = {
  primary: "Primary lockup",
  mark: "Mark",
  wordmark: "Wordmark",
  horizontal: "Horizontal lockup",
  stacked: "Stacked lockup",
  "mono-dark": "Mono dark",
  "mono-light": "Mono light",
  favicon: "Favicon / app icon",
};

export const VARIANT_ORDER: LogoVariantKey[] = ["primary", "horizontal", "stacked", "mark", "wordmark", "mono-dark", "mono-light", "favicon"];

export function kitReadme(genome: Genome, variants: KitVariant[], opts: KitOptions): string {
  const logo = genome.visual.logo;
  const lines: string[] = [];
  lines.push(`${genome.name} — Logo kit`);
  lines.push("=".repeat(Math.max(12, genome.name.length + 11)));
  lines.push("");
  lines.push(`Generated by Ligature on ${new Date().toISOString().slice(0, 10)}.`);
  if (logo.concept) {
    lines.push("");
    lines.push("Concept");
    lines.push(`  ${logo.concept}`);
  }
  lines.push("");
  lines.push("Contents");
  for (const v of variants) {
    const s = svgSize(v.svg);
    lines.push(`  svg/${v.key}.svg  (${Math.round(s.width)}×${Math.round(s.height)} units) — ${v.label ?? VARIANT_LABELS[v.key as LogoVariantKey] ?? v.key}`);
  }
  if (opts.includePng !== false) {
    const scales = opts.scales ?? [1, 2, 4];
    const base = opts.baseWidth ?? 512;
    lines.push(`  png/<variant>@${scales.map((s) => `${s}x`).join("|")}.png — transparent PNGs, @1x is ${base}px wide`);
  }
  if (opts.includeFavicon !== false) {
    lines.push("  favicon/favicon.ico (16/32/48), apple-touch-icon-180.png, icon-192.png, icon-512.png");
  }
  lines.push("");
  lines.push("Clearspace");
  lines.push(`  Keep ${logo.clearspaceMultiplier}x clear on every side, where x = a quarter of the logo height.`);
  lines.push("");
  lines.push("Minimum size");
  lines.push(`  Screen: ${logo.minSizePx}px wide · Print: ${logo.minSizeMm}mm wide. Use the mark alone below that.`);
  if (logo.usageRules.length) {
    lines.push("");
    lines.push("Usage");
    for (const r of logo.usageRules) lines.push(`  • ${r}`);
  }
  if (logo.doNots.length) {
    lines.push("");
    lines.push("Don't");
    for (const r of logo.doNots) lines.push(`  ✕ ${r}`);
  }
  const colors = genome.visual.palette.colors;
  if (colors.length) {
    lines.push("");
    lines.push("Brand colours");
    for (const c of colors) lines.push(`  ${c.hex.toUpperCase()}  ${c.name}${c.role !== "custom" ? ` (${c.role})` : ""}`);
  }
  lines.push("");
  lines.push("Fonts");
  lines.push(`  Display: ${genome.visual.typography.display.family} · Body: ${genome.visual.typography.body.family}`);
  lines.push("");
  return lines.join("\n");
}

/** Build the ZIP kit. Returns a Blob ready for download. */
export async function buildLogoKit(genome: Genome, variants: KitVariant[], opts: KitOptions = {}): Promise<Blob> {
  if (!variants.length) throw new Error("No logo variants to export");
  const { default: JSZip } = await import("jszip");
  const zip = new JSZip();
  const scales = opts.scales ?? [1, 2, 4];
  const baseWidth = opts.baseWidth ?? 512;
  const includePng = opts.includePng !== false;
  const includeFavicon = opts.includeFavicon !== false;
  const total = variants.length * (1 + (includePng ? scales.length : 0)) + (includeFavicon ? 5 : 0) + 1;
  let done = 0;
  const tick = (msg: string) => {
    done += 1;
    opts.onProgress?.(msg, done / total);
  };

  const svgDir = zip.folder("svg")!;
  const pngDir = includePng ? zip.folder("png")! : null;
  for (const v of variants) {
    svgDir.file(`${v.key}.svg`, v.svg);
    tick(`svg/${v.key}.svg`);
    if (pngDir) {
      for (const s of scales) {
        const w = Math.round(baseWidth * s);
        const bg = v.key === "mono-light" ? opts.monoLightBackground : undefined;
        const png = await svgToPngBlob(v.svg, w, undefined, bg ? { background: bg, padding: Math.round(w * 0.06) } : {});
        pngDir.file(`${v.key}@${s}x.png`, png);
        tick(`png/${v.key}@${s}x.png`);
      }
    }
  }

  if (includeFavicon) {
    const icon = variants.find((v) => v.key === "favicon") ?? variants.find((v) => v.key === "mark") ?? variants[0];
    const favDir = zip.folder("favicon")!;
    const sizes = [16, 32, 48] as const;
    const pngs: { size: number; blob: Blob }[] = [];
    for (const size of sizes) {
      pngs.push({ size, blob: await svgToPngBlob(icon.svg, size, size) });
      tick(`favicon ${size}px`);
    }
    favDir.file("favicon.ico", await pngsToIco(pngs));
    favDir.file("apple-touch-icon-180.png", await svgToPngBlob(icon.svg, 180, 180));
    tick("apple-touch-icon");
    favDir.file("icon-192.png", await svgToPngBlob(icon.svg, 192, 192));
    favDir.file("icon-512.png", await svgToPngBlob(icon.svg, 512, 512));
    tick("web app icons");
    favDir.file(
      "manifest-snippet.json",
      JSON.stringify(
        {
          name: genome.name,
          icons: [
            { src: "icon-192.png", sizes: "192x192", type: "image/png" },
            { src: "icon-512.png", sizes: "512x512", type: "image/png" },
          ],
        },
        null,
        2,
      ),
    );
  }

  zip.file("README.txt", kitReadme(genome, variants, opts));
  tick("README");
  return zip.generateAsync({ type: "blob", compression: "DEFLATE" });
}

export function kitFilename(genome: Genome): string {
  return `${slugify(genome.name)}-logo-kit.zip`;
}
